get:
  summary: Get a product by its id.
  description: Endpoint to get a product by its id.
  operationId: getProduct
  tags:
    - Product
  parameters:
    - name: id
      in: path
      description: product id
      schema:
        type: string
      required: true
  responses:
    '200':
      $ref: '../shared/responses.yml#/GetProductSuccess'
    '400':
      $ref: '../shared/responses.yml#/ValidationError'
    '404':
      $ref: '../shared/responses.yml#/NotFoundError'
    '500':
      $ref: '../shared/responses.yml#/InternalServerError'
  security:
    - auth: []

patch:
  summary: Update a product by its id.
  description: Endpoint to update the properties of a product.
  operationId: updateProduct
  tags:
    - Product
  parameters:
    - name: id
      in: path
      description: Product ID
      required: true
      schema:
        type: string
  requestBody:
    description: Product object to be updated
    required: true
    content:
      application/json:
        schema:
          $ref: '../shared/schemas.yml#/ProductItem'
  responses:
    '200':
      $ref: '../shared/responses.yml#/UpdateProductSuccess'
    '400':
      $ref: '../shared/responses.yml#/ValidationError'
    '404':
      $ref: '../shared/responses.yml#/NotFoundError'
    '500':
      $ref: '../shared/responses.yml#/InternalServerError'
  security:
    - auth: []

delete:
  summary: Delete a product by its ID
  description: Deletes a product from the system by its unique ID.
  operationId: deleteProduct
  tags:
    - Product
  parameters:
    - name: id
      in: path
      description: ID of the product to be deleted
      required: true
      schema:
        type: string
  responses:
    '204':
      description: Product deleted successfully
    '400':
      $ref: '../shared/responses.yml#/ValidationError'
    '404':
      $ref: '../shared/responses.yml#/NotFoundError'
    '500':
      $ref: '../shared/responses.yml#/InternalServerError'
  security:
    - auth: []
