get:
  summary: Get a all products, limit 20.
  description: Endpoit to get all the products
  operationId: getProducts
  tags:
    - Product

  responses:
    '200':
      $ref: '../shared/responses.yml#/GetAllProductsSuccess'
    '400':
      $ref: '../shared/responses.yml#/ValidationError'
    '404':
      $ref: '../shared/responses.yml#/NotFoundError'
    '500':
      $ref: '../shared/responses.yml#/InternalServerError'
  security:
    - auth: []
